package ulb.services;

import java.util.Random;

import ulb.Configuration;
import ulb.models.bugemon.Attack;
import ulb.models.combat.Combat;
import ulb.models.combat.CombatBugemon;
import ulb.models.combat.CombatResult;
import ulb.models.combat.CombatTeam;
import ulb.models.combat.damage.DamageCalculator;
import ulb.models.combat.damage.Efficiency;
import ulb.models.combat.strategy.AutoStrategy;
import ulb.models.combat.strategy.CombatStrategy;
import ulb.models.combat.strategy.PlayerStrategy;
import ulb.models.combat.utils.EffectProcessor;
import ulb.models.item.Inventory;
import ulb.models.run.RunTeam;
import ulb.models.team.Team;
import ulb.models.team.TeamFactory;

/**
 * Stateless utility for combat calculations: attack priority, damage formula.
 */
public class CombatService {

    private static final int BASE_XP = 30;
    private static final int BOSS_MULTIPLIER = 2;
    private static final int NORMAL_MULTIPLIER = 1;

    private final DamageCalculator damageCalculator;
    private final EffectProcessor effectProcessor;
    private final Random random;

    public CombatService(DamageCalculator damageCalculator, EffectProcessor effectProcessor, Random random) {
        this.damageCalculator = damageCalculator;
        this.effectProcessor = effectProcessor;
        this.random = random;
    }

    /**
     * Creates a combat.
     *
     * At the end of the combat, HPs are restored and XP is distributed.
     */
    public Combat createCombat(RunTeam playerRunTeam, CombatTeam opponentTeam, Inventory playerInventory,
            Inventory opponentInventory, PlayerInputHandler handler, int floor, boolean bossMode) {
        CombatTeam playerCombatTeam = CombatTeam.fromRunTeam(playerRunTeam);
        CombatStrategy playerStrategy = new PlayerStrategy(handler);
        CombatStrategy opponentStrategy = new AutoStrategy(this.random);
        return new Combat(playerCombatTeam, opponentTeam, floor, bossMode, playerInventory, opponentInventory,
                playerStrategy, opponentStrategy, this.damageCalculator, this.effectProcessor);
    }

    /**
     * Creates a combat where the player's team is also controlled by {@link AutoStrategy}.
     */
    public Combat createAutoCombat(RunTeam playerRunTeam, CombatTeam opponentTeam, Inventory playerInventory,
            Inventory opponentInventory, int floor, boolean bossMode) {
        CombatTeam playerCombatTeam = CombatTeam.fromRunTeam(playerRunTeam);
        CombatStrategy playerStrategy = new AutoStrategy(this.random);
        CombatStrategy opponentStrategy = new AutoStrategy(this.random);
        return new Combat(playerCombatTeam, opponentTeam, floor, bossMode, playerInventory, opponentInventory,
                playerStrategy, opponentStrategy, this.damageCalculator, this.effectProcessor);
    }

    /**
     * Creates a manual standalone combat; the opponent team is generated by the provided factory.
     */
    public Combat createStandaloneManualCombat(RunTeam playerRunTeam, Inventory playerInventory,
            PlayerInputHandler handler, TeamFactory opponentFactory) {
        CombatTeam opponentTeam = this.buildOpponentTeam(playerRunTeam.size(), opponentFactory);
        return this.createCombat(playerRunTeam, opponentTeam, playerInventory, new Inventory(), handler,
                Configuration.Game.FLOOR_MIN, false);
    }

    /**
     * Creates an automatic standalone combat; the opponent team is generated by the provided factory.
     */
    public Combat createStandaloneAutoCombat(RunTeam playerRunTeam, Inventory playerInventory,
            TeamFactory opponentFactory) {
        CombatTeam opponentTeam = this.buildOpponentTeam(playerRunTeam.size(), opponentFactory);
        return this.createAutoCombat(playerRunTeam, opponentTeam, playerInventory, new Inventory(),
                Configuration.Game.FLOOR_MIN, false);
    }

    private CombatTeam buildOpponentTeam(int size, TeamFactory factory) {
        Team opponentRaw = factory.create(size);
        return CombatTeam.fromRunTeam(RunTeam.fromTeam(opponentRaw));
    }

    public void finalizeCombat(Combat combat) {
        CombatTeam playerTeam = combat.getPlayerTeam();

        if (combat.getResult() == CombatResult.VICTORY) {
            int opponentCount = combat.getOpponentTeamSize();
            int totalXp = this.computeCombatXp(combat.getFloor(), combat.isBossMode(), opponentCount);
            int xpPerBugemon = this.computeXpPerBugemon(totalXp, playerTeam.size());
            playerTeam.getParticipants().forEach(participant -> participant.addXp(xpPerBugemon));
        }
    }

    public Efficiency previewEfficiency(Attack attack, CombatBugemon defender) {
        return this.damageCalculator.previewEfficiency(attack.type(), defender.getType());
    }

    // TODO: move it
    private int computeCombatXp(int floorNumber, boolean isBoss, int opponentCount) {
        int typeMultiplier = isBoss ? BOSS_MULTIPLIER : NORMAL_MULTIPLIER;
        return BASE_XP * floorNumber * typeMultiplier * opponentCount;
    }

    private int computeXpPerBugemon(int totalXp, int participantCount) {
        if (participantCount <= 0) {
            return 0;
        }
        return totalXp / participantCount;
    }
}
