package ulb.services;

import java.util.List;
import java.util.stream.IntStream;

import ulb.models.bugemon.Bugemon;
import ulb.models.level_up.LevelUp;
import ulb.models.trainer.Trainer;

/**
 * Utility class providing helper methods for level-up and experience point calculations.
 * <p>
 * Handles XP requirements per level, XP distribution after combat, and level-up processing
 * for Bugemons.
 * </p>
 * <p>
 * This class is not meant to be instantiated; all methods are static.
 * </p>
 */
public class LevelUpService {
    /**
     * Calculates the XP gained from defeating opponents in combat.
     *
     * @param floorLevel the current floor level (affects XP gain)
     * @param multiplier a multiplier based on combat conditions
     * @param opponentCount the number of opponents defeated
     * @return the total XP gained
     */
    public static int xpGain(final int floorLevel, final int multiplier, final int opponentCount) {
        return 30 * floorLevel * multiplier * opponentCount;
    }

    /**
     * Distributes XP to the winner's team after combat using default floor level and multiplier.
     * <p>
     * This is a convenience method that uses placeholder values for floor level (1) and
     * multiplier (1).
     * </p>
     *
     * @param winner the trainer who won the combat
     * @param loser the trainer who lost the combat
     * @return the LevelUps generated by awarding xp
     */
    public static List<LevelUp> distributeXpAndGetLevelUps(final Trainer winner,
                                                           final Trainer loser) {
        final int floorLevel = 1; // Placeholder for actual floor level
        final int multiplier = 1; // Placeholder for actual multiplier based on combat conditions

        return distributeXpAndGetLevelUps(winner, loser, floorLevel, multiplier);
    }

    /**
     * Distributes XP to the winner's team after combat.
     * <p>
     * XP is divided equally among all Bugemons that participated in the fight.
     * Only Bugemons that participated (as determined by {@link Bugemon#getParticipation()})
     * receive XP.
     * </p>
     *
     * @param winner the trainer who won the combat
     * @param loser the trainer who lost the combat
     * @param floor the current floor level
     * @param multiplier a multiplier based on combat conditions
     * @return the LevelUps generated by awarding xp
     */
    public static List<LevelUp> distributeXpAndGetLevelUps(final Trainer winner,
                                                           final Trainer loser, final int floor,
                                                           final int multiplier) {
        final List<Bugemon> participatingBugemon =
                winner.getTeam().stream().filter(Bugemon::getParticipation).toList();

        final int nAdversaries = loser.getTeamSize();
        final int numParticipatingBugemon = participatingBugemon.size();

        final int xpWon = xpGain(floor, multiplier, nAdversaries);
        final int xpPerBugemon = (xpWon / numParticipatingBugemon);

        // My functional bros will love this one :-D
        //
        // process each participating Bugemon and collect all level-ups
        return participatingBugemon.stream()
                .flatMap(bugemon -> {
                    int numLevelUps = bugemon.gainXp(xpPerBugemon);

                    if (numLevelUps > 0) {
                        bugemon.restoreHp();
                    }

                    // create one LevelUp object per level gained (e.g., 2 levels = 2 LevelUps)
                    return IntStream.range(0, numLevelUps).mapToObj(i -> new LevelUp(bugemon));
                })
                .toList();
    }
}
