image: maven:3.9.9-eclipse-temurin-21

stages:
  - lint
  - test
  - package

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

check-style:
  stage: lint
  before_script:
    - apt-get update && apt-get install -y clang-format
  script:
    - |
      if [ -f ".clang-format" ]; then
        echo "File .clang-format detected. Verification in progress..."
        find src -name "*.java" -exec clang-format --dry-run --Werror -style=file {} +
        echo "The code is perfectly formatted."
      else
        echo "No .clang-format file found at the root. Job skipped."
      fi
  allow_failure: true

# Job test
test:
  stage: test
  services:
    - postgres:16
  variables:
    POSTGRES_DB: bugemon_test
    POSTGRES_USER: bugemon
    POSTGRES_PASSWORD: npg_vbus4D2Yltdf
    TEST_DB_URL: "jdbc:postgresql://postgres/bugemon_test?user=bugemon&password=npg_vbus4D2Yltdf"
  script:
    - mvn clean test -DTEST_DB_URL="$TEST_DB_URL"
  artifacts:
    paths:
      - target/surefire-reports/
    expire_in: 7 days
    when: always

# Create a jar package only on the main branch (useful to give a .jar to the client)
package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days
