image: maven:4.0.0-rc-5-ibm-semeru-25-noble

stages:
  - test
  - package

cache:
  key: "$CI_COMMIT_REF_SLUG" # Separate cache for all branches
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  before_script:
    - apt-get update -y
    - apt-get install -y xvfb libx11-6 libxext6 libxrender1 libxtst6 libgtk-3-0 libgl1-mesa-glx
  script:
    - xvfb-run -a mvn clean test

# Create a jar package only on the main branch (useful to give a .jar to the client)
package:
  stage: package
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 7 days
