-- Query to create the database schema
-- CreateSchema

CREATE TABLE IF NOT EXISTS "attacks" (
  "id" varchar PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "description" varchar,
  "power" integer
);

CREATE TABLE IF NOT EXISTS "attack_effects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attack_id" varchar REFERENCES "attacks"("id") ON DELETE CASCADE,
  "type" varchar,
  "target" varchar,
  "stat" varchar,
  "modifier" integer,
  "duration" varchar,
  "amount" integer
);

CREATE TABLE IF NOT EXISTS "bugemons" (
  "name" varchar PRIMARY KEY,
  "type" varchar,
  "sprite" varchar,
  "base_defense" integer,
  "base_attack" integer,
  "base_initiative" integer,
  "base_max_hp" integer,
  "is_starter" boolean,
  "attack_1_id" varchar,
  "attack_2_id" varchar,
  "attack_3_id" varchar
);

CREATE TABLE IF NOT EXISTS "players" (
  "playername" varchar PRIMARY KEY,
  "current_team" varchar,
  "current_tower_floor" integer DEFAULT 2
);

CREATE TABLE IF NOT EXISTS "player_bugemons" (
  "playername" varchar,
  "bugemon_name" varchar,
  "current_defense" integer,
  "current_attack" integer,
  "current_initiative" integer,
  "current_max_hp" integer,
  "current_xp" integer DEFAULT 0,
  "current_level" integer DEFAULT 1,
  PRIMARY KEY ("playername", "bugemon_name")
);

CREATE TABLE IF NOT EXISTS "teams" (
  "playername" varchar,
  "name" varchar,
  PRIMARY KEY ("playername", "name")
);

CREATE TABLE IF NOT EXISTS "team_members" (
  "playername" varchar,
  "team_name" varchar,
  "bugemon_name" varchar,
  "slot_position" integer,
  PRIMARY KEY ("playername", "team_name", "slot_position")
);

CREATE TABLE IF NOT EXISTS "items" (
  "item_id" varchar,
  "name" varchar,
  "description" varchar,
  "category" varchar,
  "sprite" varchar, 
  PRIMARY KEY ("item_id")
);

CREATE TABLE IF NOT EXISTS "item_effects" (
  "item_id" varchar REFERENCES "items"("item_id") ON DELETE CASCADE,
  "type" varchar,
  "target" varchar,
  "value" integer,
  "stat" varchar,
  "modifier" integer,
  "duration" integer,
  PRIMARY KEY ("item_id")

);

CREATE TABLE IF NOT EXISTS "item_player" (
  "playername" varchar REFERENCES "players"("playername") ON DELETE CASCADE, 
  "item_id" varchar REFERENCES "items"("item_id") ON DELETE CASCADE,
  "amount" integer,
  PRIMARY KEY ("playername", "item_id")
);

CREATE UNIQUE INDEX ON "team_members" ("playername", "team_name", "bugemon_name");

ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_1_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_2_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_3_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "attack_effects" ADD FOREIGN KEY ("attack_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "player_bugemons" ADD FOREIGN KEY ("playername") REFERENCES "players" ("playername") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "player_bugemons" ADD FOREIGN KEY ("playername") REFERENCES "players" ("playername") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "player_bugemons" ADD FOREIGN KEY ("bugemon_name") REFERENCES "bugemons" ("name") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teams" ADD FOREIGN KEY ("playername") REFERENCES "players" ("playername") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "team_members" ADD FOREIGN KEY ("playername", "team_name") REFERENCES "teams" ("playername", "name") ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_playername_bugemon_name_fkey" FOREIGN KEY ("playername", "bugemon_name") REFERENCES "player_bugemons" ("playername", "bugemon_name") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "item_player" ADD FOREIGN KEY ("playername") REFERENCES "players"("playername") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "item_player" ADD FOREIGN KEY ("item_id") REFERENCES "items"("item_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "teams" ADD FOREIGN KEY ("playername") REFERENCES "players" ("playername") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "players" ADD FOREIGN KEY ("playername", "current_team") REFERENCES "teams" ("playername", "name") DEFERRABLE INITIALLY IMMEDIATE;
