-- Query to create the database schema
-- CreateSchema

CREATE TABLE IF NOT EXISTS "attacks" (
  "id" varchar PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "description" varchar,
  "power" integer
);

CREATE TABLE IF NOT EXISTS "attack_effects" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "attack_id" varchar REFERENCES "attacks"("id") ON DELETE CASCADE,
  "type" varchar,
  "target" varchar,
  "stat" varchar,
  "modifier" integer,
  "duration" varchar,
  "amount" integer
);

CREATE TABLE IF NOT EXISTS "bugemons" (
  "id" varchar PRIMARY KEY,
  "name" varchar,
  "type" varchar,
  "sprite" varchar,
  "base_defense" integer,
  "base_attack_power" integer,
  "base_initiative" integer,
  "base_max_hp" integer,
  "is_starter" boolean,
  "attack_1_id" varchar,
  "attack_2_id" varchar,
  "attack_3_id" varchar
);

CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS "user_bugemons" (
  "user_id" integer,
  "bugemon_id" varchar,
  "current_defense" integer,
  "current_attack_power" integer,
  "current_initiative" integer,
  "current_max_hp" integer,
  "current_xp" integer DEFAULT 0,
  "current_level" integer DEFAULT 1,
  PRIMARY KEY ("user_id", "bugemon_id")
);

CREATE TABLE IF NOT EXISTS "teams" (
  "user_id" integer,
  "name" varchar,
  PRIMARY KEY ("user_id", "name")
);

CREATE TABLE IF NOT EXISTS "team_members" (
  "user_id" integer,
  "team_name" varchar,
  "bugemon_id" varchar,
  "slot_position" integer,
  PRIMARY KEY ("user_id", "team_name", "slot_position")
);

CREATE UNIQUE INDEX ON "team_members" ("user_id", "team_name", "bugemon_id");

ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_1_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_2_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "bugemons" ADD FOREIGN KEY ("attack_3_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "attack_effects" ADD FOREIGN KEY ("attack_id") REFERENCES "attacks" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user_bugemons" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "user_bugemons" ADD FOREIGN KEY ("bugemon_id") REFERENCES "bugemons" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "teams" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "team_members" ADD FOREIGN KEY ("user_id", "team_name") REFERENCES "teams" ("user_id", "name") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "team_members" ADD FOREIGN KEY ("user_id", "bugemon_id") REFERENCES "user_bugemons" ("user_id", "bugemon_id") DEFERRABLE INITIALLY IMMEDIATE;
