package ulb.controllers;

import java.io.IOException;
import java.util.List;

import ulb.controllers.MetaController.Window;
import ulb.models.level_up.Choice;
import ulb.models.level_up.LevelUp;
import ulb.views.LevelUpView;

/**
 * Controller responsible for the level-up screen shown after a victorious combat
 * when one or more of the player's {@link ulb.models.bugemon.Bugemon}s have
 * accumulated enough XP to advance to the next level.
 *
 * <p>
 * {@code LevelUpController} processes a sequential list of {@link LevelUp}
 * events, one per Bugemon that levelled up. For each event it populates the
 * {@link LevelUpView} with the three stat-bonus choices generated by
 * {@link LevelUp#getChoices()}, waits for the player to pick one via
 * {@link #chooseOption(int)}, applies the chosen bonus to the Bugemon, and
 * then advances to the next event (or navigates to the victory screen when all
 * events have been handled).
 * </p>
 *
 * <p>
 * The list of pending level-up events is supplied by
 * {@link MetaController#setLevelUp(List)}, which delegates to
 * {@link #setLevelUp(List)}. If the list is empty, the method skips the
 * level-up screen entirely and navigates directly to
 * {@link Window#COMBAT_VICTORY}.
 * </p>
 *
 * @see LevelUp
 * @see LevelUpView
 * @see MetaController
 * @see Controller
 */
public class LevelUpController extends Controller<LevelUpView> {
    /** The ordered list of level-up events to process, one per levelled-up Bugemon. */
    List<LevelUp> levelUps;

    /** Zero-based index of the {@link LevelUp} event currently displayed. */
    int currentIdx;

    /**
     * Constructs a {@code LevelUpController}, initialises its {@link LevelUpView},
     * and registers this controller as the view's event handler.
     *
     * <p>
     * The view is instantiated here so that its FXML layout is loaded and its
     * scene graph is ready before the controller is used for the first time.
     * </p>
     *
     * @param metaController the application-level {@link MetaController} used for
     *                       screen navigation; must not be {@code null}.
     * @throws IOException if the {@link LevelUpView} fails to load its FXML
     *                     resource.
     */
    public LevelUpController(MetaController metaController) throws IOException {
        super(metaController, new LevelUpView());
        this.view.setController(this);
    }

    /**
     * Callback invoked when the player selects one of the three stat-bonus options
     * offered during a level-up event.
     *
     * <p>
     * Retrieves the current {@link LevelUp} event from {@link #levelUps}, extracts
     * the {@link Choice} at the given index, applies it to the levelling-up
     * {@link ulb.models.bugemon.Bugemon} via
     * {@link ulb.models.bugemon.Bugemon#applyChoice(Choice)}, and then advances
     * to the next event by calling {@link #cont()}.
     * </p>
     *
     * @param optionIdx the zero-based index of the chosen option (typically
     *                  {@code 0}, {@code 1}, or {@code 2}); must be a valid
     *                  index into the current event's choice list.
     */
    public void chooseOption(int optionIdx) {
        LevelUp levelUp = this.levelUps.get(this.currentIdx);
        List<Choice> choices = levelUp.getChoices();
        Choice choice = choices.get(optionIdx);
        levelUp.getBugemon().applyChoice(choice);
        this.cont();
    }

    /**
     * Initialises the controller with the given list of level-up events and
     * navigates to the level-up screen if the list is non-empty.
     *
     * <p>
     * If {@code lvlsUp} is non-empty, the internal index is reset to {@code 0},
     * the view is populated with the first event, and the application transitions
     * to {@link Window#LEVEL_UP}. If {@code lvlsUp} is empty, no level-ups need
     * to be handled and the application navigates directly to
     * {@link Window#COMBAT_VICTORY}.
     * </p>
     *
     * @param lvlsUp the ordered list of {@link LevelUp} events to process;
     *               must not be {@code null}, but may be empty.
     */
    public void setLevelUp(List<LevelUp> lvlsUp) {
        if (!lvlsUp.isEmpty()) {
            this.levelUps = lvlsUp;
            this.currentIdx = 0;
            this.view.setLevelUp(this.levelUps.get(this.currentIdx));
            this.metaController.switchTo(Window.LEVEL_UP);
        } else {
            this.metaController.switchTo(Window.COMBAT_VICTORY);
        }
    }

    /**
     * Advances to the next pending level-up event, or navigates to the victory
     * screen if all events have been handled.
     *
     * <p>
     * Increments {@link #currentIdx}. If there is another event in the list, the
     * view is refreshed with that event's data. Otherwise the application
     * transitions to {@link Window#COMBAT_VICTORY}.
     * </p>
     *
     * <p>
     * The name {@code cont} is short for <em>continue</em>, since {@code continue}
     * is a reserved keyword in Java.
     * </p>
     */
    public void cont() {
        this.currentIdx++;
        if (this.currentIdx < this.levelUps.size()) {
            this.view.setLevelUp(this.levelUps.get(this.currentIdx));
        } else {
            this.metaController.switchTo(Window.COMBAT_VICTORY);
            // TODO: see with client, this.metaController.resetTeam();
        }
    }
}
